version: 2

updates:
- package-ecosystem: npm
  directory: "/scraper"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  commit-message:
    prefix: "npm"
    include: "scope"
  groups:
    dependencies-patch-and-minor:
      update-types:
        - minor
        - patch
  open-pull-requests-limit: 50
  reviewers:
  - fabrice404
  assignees:
  - fabrice404

- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  commit-message:
    prefix: "npm"
    include: "scope"
  groups:
    dependencies-patch-and-minor:
      update-types:
        - minor
        - patch
  open-pull-requests-limit: 50
  reviewers:
  - fabrice404
  assignees:
  - fabrice404
